const RATE_MY_PROFESSOR_DATA = {
    "Hall-Holt, Olaf": {
        id: "479493",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "17",
    },
    "Wells, Colin": {
        id: "24808",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "80",
    },
    "Judge, Rebecca": {
        id: "55473",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "15",
    },
    "Carter, David": {
        id: "55475",
        rating: "4.4",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "67",
    },
    "Carullo, Sylvia": {
        id: "69265",
        rating: "2.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "60",
    },
    "May, James": {
        id: "69267",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "---",
    },
    "Emery, Mary": {
        id: "69269",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Pomponio, Xun": {
        id: "69270",
        rating: "2.3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "17",
    },
    "Schodt, David": {
        id: "69272",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "---",
    },
    "Allen, Wendy": {
        id: "117405",
        rating: "3.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "50",
    },
    "Freeman, Dona": {
        id: "117407",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "67",
    },
    "Brown, Richard": {
        id: "117409",
        rating: "2.6",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "25",
    },
    "Niemisto, Paul": {
        id: "125658",
        rating: "2.8",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "---",
    },
    "Hanson, Alice": {
        id: "125660",
        rating: "4",
        reviews: 0,
        difficulty: "4.9",
        wouldTakeAgain: "---",
    },
    "McMillan, Donna": {
        id: "129549",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "100",
    },
    "Santurri, Ed": {
        id: "129555",
        rating: "4",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "100",
    },
    "Cole, Eric": {
        id: "138619",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Holly, Carol": {
        id: "141510",
        rating: "4",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Johnson, Ted": {
        id: "156253",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "---",
    },
    "Kermott, Henry": {
        id: "156258",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Booth, David": {
        id: "159978",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "91",
    },
    "Sabo, Ana": {
        id: "159985",
        rating: "2.3",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Sera, Maria": {
        id: "162793",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Thorsheim, Howard": {
        id: "170276",
        rating: "2.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Peters, Dolores": {
        id: "170753",
        rating: "4",
        reviews: 0,
        difficulty: "4.5",
        wouldTakeAgain: "50",
    },
    "Soderlind, Steve": {
        id: "177193",
        rating: "4.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Anderson, Deborah": {
        id: "177194",
        rating: "2.7",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "---",
    },
    "Bakko, Gene": {
        id: "196596",
        rating: "4.4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Swift, Michael": {
        id: "196604",
        rating: "3.1",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "---",
    },
    "Leblanc, Diane": {
        id: "197790",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Shea, Kathy": {
        id: "197885",
        rating: "1.9",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Porterfield, Jean": {
        id: "197886",
        rating: "4.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Hanson, Bruce": {
        id: "197888",
        rating: "4.4",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Broner, Maggie": {
        id: "197889",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "100",
    },
    "Rohn, Matt": {
        id: "197890",
        rating: "2.6",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "50",
    },
    "Kolan, Amy": {
        id: "197894",
        rating: "3.8",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "50",
    },
    "Allen, Richard": {
        id: "198048",
        rating: "1.8",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "50",
    },
    "Ito, Rika": {
        id: "199727",
        rating: "3.9",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Entenmann, Robert": {
        id: "199731",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "---",
    },
    "Riley, Patrick": {
        id: "199734",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "100",
    },
    "Lynd, Juliet": {
        id: "199735",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Taliaferro, Charles": {
        id: "208334",
        rating: "4.1",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "90",
    },
    "Aarsvold, Nancy": {
        id: "208336",
        rating: "4.4",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "---",
    },
    "Benson, Pastor": {
        id: "208337",
        rating: "4.9",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "100",
    },
    "Nesbit, Coach": {
        id: "208338",
        rating: "5",
        reviews: 0,
        difficulty: "1.2",
        wouldTakeAgain: "100",
    },
    "Richey, Matthew": {
        id: "220376",
        rating: "4",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "59",
    },
    "Arneson, Wendell": {
        id: "220385",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Kucera, Karil": {
        id: "220387",
        rating: "4.6",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "100",
    },
    "Hanson, Robert": {
        id: "231356",
        rating: "3",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "50",
    },
    "Williamson, Tom": {
        id: "241975",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "75",
    },
    "Armstrong, Anton": {
        id: "250538",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Amundson, Steven": {
        id: "261059",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Rippley, Vern": {
        id: "261062",
        rating: "2.8",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Poehlmann, William": {
        id: "261063",
        rating: "3.7",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Humke, Paul": {
        id: "261064",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Dietz, Jill": {
        id: "262349",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "84",
    },
    "Hofrenning, Dan": {
        id: "262351",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "50",
    },
    "Wilson, Charles": {
        id: "268464",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "75",
    },
    "Hahn, Steve": {
        id: "275053",
        rating: "3.9",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "75",
    },
    "Jacobel, Robert": {
        id: "282213",
        rating: "3.1",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Cropsey, Kris": {
        id: "282596",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "88",
    },
    "Reed, Barbara": {
        id: "308121",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "100",
    },
    "Smith, Andrew": {
        id: "309381",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Bauer, Susan": {
        id: "316925",
        rating: "2.8",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Buckstead, Richard": {
        id: "317885",
        rating: "2.6",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Cherewatuk, Karen": {
        id: "317888",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "100",
    },
    "Marsalek, Karen": {
        id: "317910",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "55",
    },
    "Dickinson, Shelly": {
        id: "321960",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Giannini, John": {
        id: "327398",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "91",
    },
    "Sonnega, Bill": {
        id: "340383",
        rating: "3.2",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Harper, Vicki": {
        id: "344813",
        rating: "3.2",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Johnson, Sigrid": {
        id: "344823",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "McKelvey, Steve": {
        id: "345162",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "---",
    },
    "Mbele, Joseph": {
        id: "350774",
        rating: "3.2",
        reviews: 0,
        difficulty: "1.5",
        wouldTakeAgain: "89",
    },
    "Groton, Anne": {
        id: "350805",
        rating: "4.1",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "67",
    },
    "Forsberg, Charles": {
        id: "350815",
        rating: "2.8",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Jackson, Paul": {
        id: "351320",
        rating: "4.1",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "---",
    },
    "Abdella, Beth": {
        id: "353567",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "67",
    },
    "Lott, Anthony": {
        id: "356555",
        rating: "4.4",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "80",
    },
    "Brunelle, Chris": {
        id: "356562",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "100",
    },
    "Hill, Jonathan": {
        id: "361812",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Steen, Mary": {
        id: "368012",
        rating: "2.1",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Durocher, Rich": {
        id: "375384",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Gervais, Karen": {
        id: "380627",
        rating: "1.8",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Strichartz, Ariel": {
        id: "383447",
        rating: "4",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "89",
    },
    "Fitzgerald, Michael": {
        id: "386746",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "75",
    },
    "Hagedorn, Dave": {
        id: "390589",
        rating: "4.6",
        reviews: 0,
        difficulty: "1.5",
        wouldTakeAgain: "100",
    },
    "Griep, Mary": {
        id: "391867",
        rating: "3.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Saurer, John": {
        id: "391874",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "84",
    },
    "Gisselman, Gary": {
        id: "393681",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.1",
        wouldTakeAgain: "---",
    },
    "Fink, Karl": {
        id: "395128",
        rating: "3.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Becker, Anthony": {
        id: "396317",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "75",
    },
    "Homstad, Torild": {
        id: "403304",
        rating: "2.2",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Bolstad, Peder": {
        id: "405111",
        rating: "1.5",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "---",
    },
    "Trull, Mary": {
        id: "405439",
        rating: "4",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Klopchin, Heather": {
        id: "410390",
        rating: "4.8",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "67",
    },
    "Langerak, Edward": {
        id: "410477",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Spessard, Gary": {
        id: "410591",
        rating: "4.5",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "---",
    },
    "Thalhammer, Kris": {
        id: "410596",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "75",
    },
    "Angell, Diane": {
        id: "410597",
        rating: "2.8",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "34",
    },
    "Schillinger, Jamie": {
        id: "410612",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "67",
    },
    "Barjasteh, Jolene": {
        id: "410679",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Breen, Sheri": {
        id: "410685",
        rating: "4",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Legler, Julie": {
        id: "411142",
        rating: "3.3",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Muth, Gregory": {
        id: "411492",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "58",
    },
    "Allister, Mark": {
        id: "411981",
        rating: "3.1",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "34",
    },
    "Thompson, Nancy": {
        id: "412232",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "50",
    },
    "Miessler, Gary": {
        id: "414047",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Hodel, Martin": {
        id: "416958",
        rating: "4.9",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Stansell, Gary": {
        id: "416961",
        rating: "3.4",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Walter, Anne": {
        id: "417380",
        rating: "3.8",
        reviews: 0,
        difficulty: "4.6",
        wouldTakeAgain: "---",
    },
    "Eaton, Muir": {
        id: "418096",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Wan, Pin": {
        id: "418101",
        rating: "3.9",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Schwinefus, Jeff": {
        id: "418106",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Carrington, Laurel": {
        id: "418269",
        rating: "3.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Zorn, Paul": {
        id: "426196",
        rating: "4.6",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Dell, Irve": {
        id: "440398",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Farrell, Jim": {
        id: "441191",
        rating: "4.4",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Larson, Phyllis": {
        id: "458001",
        rating: "4.9",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Galbraith, Elizabeth": {
        id: "469845",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "---",
    },
    "Howe, Timothy": {
        id: "470802",
        rating: "3.6",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "91",
    },
    "Narvaez, Leon": {
        id: "473513",
        rating: "3.1",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "34",
    },
    "Saterstrom, Sheryl": {
        id: "475554",
        rating: "4.3",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "---",
    },
    "Hauck, Robert": {
        id: "475690",
        rating: "4.1",
        reviews: 0,
        difficulty: "2.1",
        wouldTakeAgain: "---",
    },
    "Muir, Gary": {
        id: "475692",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Lagerquist, Deane": {
        id: "475701",
        rating: "2.8",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "30",
    },
    "Mather, Clare": {
        id: "475704",
        rating: "3.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Merritt, Justin": {
        id: "477023",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Kandl, Kim": {
        id: "477604",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Rudd, Anthony": {
        id: "477646",
        rating: "2.9",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Achberger, Karen": {
        id: "477913",
        rating: "1.9",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "30",
    },
    "Hill, Janet": {
        id: "477916",
        rating: "3.7",
        reviews: 0,
        difficulty: "2.1",
        wouldTakeAgain: "---",
    },
    "Anderson, Carolyn": {
        id: "477918",
        rating: "2.8",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "---",
    },
    "Anderson, Kurt": {
        id: "477919",
        rating: "2.8",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Bader, Jennifer": {
        id: "477922",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "100",
    },
    "Berger, Linda": {
        id: "477930",
        rating: "4.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Beussman, Douglass": {
        id: "477931",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Barbour, John": {
        id: "477932",
        rating: "3.8",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Bjorklund, Brian": {
        id: "477934",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "100",
    },
    "Chiappari, Christopher": {
        id: "477937",
        rating: "3.4",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "100",
    },
    "Postlethwaite, Diana": {
        id: "479565",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "---",
    },
    "Kutulas, Judy": {
        id: "479709",
        rating: "2.8",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Reece, Steve": {
        id: "481462",
        rating: "4.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Neal, Diana": {
        id: "482015",
        rating: "4",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Gross, Dana": {
        id: "482317",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Nichol, Todd": {
        id: "482503",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Zempel, Solveig": {
        id: "482505",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Hoekstra, Gerald": {
        id: "482832",
        rating: "2.7",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Nitz, David": {
        id: "488159",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "67",
    },
    "Roback, Paul": {
        id: "490072",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Elkina, Julia": {
        id: "495070",
        rating: "2.7",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "15",
    },
    "Dahl, David": {
        id: "495977",
        rating: "3.8",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Wojick, Paul": {
        id: "507703",
        rating: "3.8",
        reviews: 0,
        difficulty: "2.1",
        wouldTakeAgain: "100",
    },
    "Walczak, Mary": {
        id: "507718",
        rating: "3.1",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Kelly, Maria": {
        id: "513458",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "---",
    },
    "Grenberg, Jeanine": {
        id: "517124",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "40",
    },
    "Leming, Mike": {
        id: "520910",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Robinson, Marc": {
        id: "523479",
        rating: "4",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Wallace, Martha": {
        id: "523562",
        rating: "2.4",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Huff, Chuck": {
        id: "529214",
        rating: "3.5",
        reviews: 0,
        difficulty: "2.1",
        wouldTakeAgain: "40",
    },
    "Carlsen, Mary": {
        id: "532119",
        rating: "4.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Schuurman, Doug": {
        id: "540131",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "67",
    },
    "Kosmoski, Dan": {
        id: "541098",
        rating: "4.2",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "100",
    },
    "Dickson, James": {
        id: "547623",
        rating: "2.7",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Hepburn, Joan": {
        id: "560785",
        rating: "2.7",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Walter, Irina": {
        id: "563888",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Malvadkar, Urmila": {
        id: "572422",
        rating: "1.5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Evans, Barb": {
        id: "593825",
        rating: "2.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Anderson, Mary": {
        id: "594064",
        rating: "3.6",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "---",
    },
    "Vonbibra, Anne": {
        id: "595362",
        rating: "3.3",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "100",
    },
    "McWilliams, Kent": {
        id: "596291",
        rating: "5",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Walter, Greg": {
        id: "599348",
        rating: "3.8",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Forstner, Dan": {
        id: "610804",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "---",
    },
    "Ripley, Jason": {
        id: "622271",
        rating: "4",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "34",
    },
    "Smith, Kay": {
        id: "640485",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Aspaas, Christopher": {
        id: "663046",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Hisey, Andrew": {
        id: "687881",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Schade, John": {
        id: "692149",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Rambachan, Anant": {
        id: "733828",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Kuxhausen, Anna": {
        id: "741407",
        rating: "4",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "67",
    },
    "Swain, Corliss": {
        id: "741878",
        rating: "3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "Marino, Gordon": {
        id: "741992",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "Garrett, Tina": {
        id: "745105",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Crisp, Kevin": {
        id: "749777",
        rating: "4",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "100",
    },
    "Kohnen, Christine": {
        id: "760600",
        rating: "1.3",
        reviews: 0,
        difficulty: "4.4",
        wouldTakeAgain: "---",
    },
    "Pensec, Herve": {
        id: "773188",
        rating: "1.5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Leming, Ann": {
        id: "786492",
        rating: "2.3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Rich, Pele": {
        id: "790968",
        rating: "2.5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Casson, Douglas": {
        id: "793016",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Jothen, Peder": {
        id: "793197",
        rating: "4",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "88",
    },
    "Fruehling, Sara": {
        id: "809475",
        rating: "3.5",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "72",
    },
    "Muir, Sian": {
        id: "817527",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "McKeel, James": {
        id: "818829",
        rating: "4.9",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Ziegler, Kathryn": {
        id: "824678",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "67",
    },
    "McClure, Robert": {
        id: "2515024",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Hayaki, Jumi": {
        id: "837061",
        rating: "4.4",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Dobbs, Jennifer": {
        id: "837505",
        rating: "4.4",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "100",
    },
    "Delaney, Jeane": {
        id: "837590",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "86",
    },
    "Welckle, John": {
        id: "850856",
        rating: "3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Sheppard, Ryan": {
        id: "866196",
        rating: "2.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "29",
    },
    "Olson, Barbara": {
        id: "879676",
        rating: "3.9",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "---",
    },
    "Edwards, Todd": {
        id: "886573",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Ufferman, Eric": {
        id: "899998",
        rating: "3.6",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "---",
    },
    "Beckman, Patricia": {
        id: "902907",
        rating: "4.1",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "75",
    },
    "Olofsson, Stefan": {
        id: "905440",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Engbrecht, Jason": {
        id: "919039",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Keuseman, Kristopher": {
        id: "919092",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Freedberg, Steven": {
        id: "920343",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "100",
    },
    "Atzinger, Christopher": {
        id: "933791",
        rating: "4.3",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "67",
    },
    "Beld, Jo": {
        id: "933959",
        rating: "1.8",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "---",
    },
    "Ferguson, John": {
        id: "944209",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Stromayer, Judy": {
        id: "948504",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Vessey, Ted": {
        id: "955957",
        rating: "3.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Willcoxon, Jeanne": {
        id: "955963",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "---",
    },
    "Runge, Stephen": {
        id: "957279",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Dale, Patrick": {
        id: "971936",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Storry, Mark": {
        id: "1000079",
        rating: "4.3",
        reviews: 0,
        difficulty: "1.8",
        wouldTakeAgain: "---",
    },
    "Emery, David": {
        id: "1000755",
        rating: "3.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Dur, Karen": {
        id: "1016640",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Hurlbutt, Jerri": {
        id: "1020780",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Ohnesorge, Clark": {
        id: "1036984",
        rating: "2.4",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Davenport, Nicholas": {
        id: "1037117",
        rating: "3.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Gundacker, Rose": {
        id: "1042442",
        rating: "4.6",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "---",
    },
    "Schaefle, Nathaniel": {
        id: "1042801",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "---",
    },
    "Chen, Luying": {
        id: "1049589",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "---",
    },
    "Smith, Robert": {
        id: "1064422",
        rating: "3.2",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Reisetter, Angela": {
        id: "1069972",
        rating: "3.1",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "---",
    },
    "Schwehn, Kaethe": {
        id: "1076045",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "100",
    },
    "Sherman, Bonnie": {
        id: "1077210",
        rating: "3.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Qian, Jun": {
        id: "1086586",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Carlson, Kerri": {
        id: "1102320",
        rating: "1.5",
        reviews: 0,
        difficulty: "5",
        wouldTakeAgain: "---",
    },
    "Hertel, Andy": {
        id: "1106716",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Lie, Kari": {
        id: "1115019",
        rating: "4.1",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "100",
    },
    "Mehta, Shefali": {
        id: "1125959",
        rating: "5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "---",
    },
    "Ryan, David": {
        id: "1141088",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Bekhechi, Amine": {
        id: "1151442",
        rating: "2.6",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "30",
    },
    "Benjamin, Mara": {
        id: "1187566",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "34",
    },
    "Pellino, Janice": {
        id: "1189498",
        rating: "3.4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Conbere, Nicholas": {
        id: "1189506",
        rating: "3.5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "---",
    },
    "Kuehn, Mary": {
        id: "1201742",
        rating: "2.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Haerter, Christine": {
        id: "1207764",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "67",
    },
    "Mader, James": {
        id: "1214059",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Orman, Cuneyt": {
        id: "1229227",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Schmidt, Stephanie": {
        id: "1229836",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "---",
    },
    "Hoogenboom, Tomoko": {
        id: "1237563",
        rating: "4.2",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "---",
    },
    "Orina, Minda": {
        id: "1260604",
        rating: "3.5",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "---",
    },
    "Pappas, Christopher": {
        id: "1266973",
        rating: "2.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Woo, Alexander": {
        id: "1272996",
        rating: "3",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "---",
    },
    "Weimerskirch, Mike": {
        id: "1312469",
        rating: "4.1",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Jorenby, Marnie": {
        id: "1321335",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Hoy, Lise": {
        id: "1332016",
        rating: "4.8",
        reviews: 0,
        difficulty: "1.7",
        wouldTakeAgain: "---",
    },
    "Atwell, Ryan": {
        id: "1337011",
        rating: "2",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Kaupp, Steffen": {
        id: "1341005",
        rating: "4.7",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Slocum, Fure": {
        id: "1344428",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Gittins, Peter": {
        id: "1346805",
        rating: "3",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "67",
    },
    "Wambheim, Bruce": {
        id: "1348767",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Hanson, James": {
        id: "1352164",
        rating: "3.9",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "91",
    },
    "Iddrisu, Abdulai": {
        id: "1352994",
        rating: "2.5",
        reviews: 0,
        difficulty: "1.9",
        wouldTakeAgain: "38",
    },
    "Chapp, Chris": {
        id: "1363372",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Bresnan, Mark": {
        id: "1370048",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "---",
    },
    "Alexander, Torrin": {
        id: "1377200",
        rating: "3",
        reviews: 0,
        difficulty: "1.7",
        wouldTakeAgain: "---",
    },
    "Solomon, Jeff": {
        id: "1377202",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Letang, Delia": {
        id: "1400501",
        rating: "4.8",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "---",
    },
    "Stern, Craig": {
        id: "1401241",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Kim, Hunjoon": {
        id: "1404691",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Berliner, Adam": {
        id: "1405645",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Alvarez, Guido": {
        id: "1406290",
        rating: "3",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "100",
    },
    "Tradowsky, Christopher": {
        id: "1407170",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "79",
    },
    "Strong, Nikki": {
        id: "1412444",
        rating: "1.2",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Sampson, Michael": {
        id: "1420567",
        rating: "5",
        reviews: 0,
        difficulty: "5",
        wouldTakeAgain: "---",
    },
    "Listenberger, Laura": {
        id: "1444746",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "84",
    },
    "Dalgaard, Bruce": {
        id: "1447915",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "---",
    },
    "Campell, Heather": {
        id: "1482339",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Cho, Grace": {
        id: "1482452",
        rating: "4.2",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "60",
    },
    "Loebach, Jeremy": {
        id: "1483083",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Cunningham, Arthur": {
        id: "1483297",
        rating: "4.1",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "91",
    },
    "Klein, Jennifer": {
        id: "1491183",
        rating: "1.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Hoover, Elizabeth": {
        id: "1492760",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Roberts, William": {
        id: "1493051",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "75",
    },
    "Epp, Erik": {
        id: "1493353",
        rating: "2.3",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "---",
    },
    "McDougall, Adam": {
        id: "1494452",
        rating: "4.6",
        reviews: 0,
        difficulty: "1.6",
        wouldTakeAgain: "---",
    },
    "Jordan, Annalisa": {
        id: "1499474",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Campbell, Heather": {
        id: "1503650",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Roberts, Anthony": {
        id: "1509314",
        rating: "3",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "34",
    },
    "Brekke, Luke": {
        id: "1516075",
        rating: "5",
        reviews: 0,
        difficulty: "5",
        wouldTakeAgain: "---",
    },
    "Matsuura, Ryota": {
        id: "1520615",
        rating: "4.8",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Chandran, Devyani": {
        id: "1540223",
        rating: "4.3",
        reviews: 0,
        difficulty: "1.5",
        wouldTakeAgain: "---",
    },
    "Fisher, Kathryne": {
        id: "1546572",
        rating: "2.6",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "---",
    },
    "Hamilton, Maya": {
        id: "1547937",
        rating: "4",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Haugsland, Jessica": {
        id: "1561493",
        rating: "4.1",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Gray, Charles": {
        id: "1579500",
        rating: "5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Hendriks, Henriet": {
        id: "1614875",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Goedde, Rick": {
        id: "1627248",
        rating: "3.8",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "67",
    },
    "Broberg, Kirstin": {
        id: "1627713",
        rating: "2.6",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Glazebrook, Rita": {
        id: "1628514",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Anderson, Kim": {
        id: "1629599",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Hodgson, Ashley": {
        id: "1636046",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "78",
    },
    "Giannini, Claudia": {
        id: "1636985",
        rating: "4.8",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Richards, Rebecca": {
        id: "1639115",
        rating: "4.6",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "89",
    },
    "Canella, Shannon": {
        id: "1639120",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Pierse, Ian": {
        id: "1641098",
        rating: "3.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Resnick, Tamar": {
        id: "1659186",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Kalyani, Dipannita": {
        id: "1670020",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "100",
    },
    "Martsberger, Carolyn": {
        id: "1675177",
        rating: "2.9",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "---",
    },
    "Pierce, Ian": {
        id: "1675383",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Blanchard, Peter": {
        id: "1677190",
        rating: "2.4",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Keefe, Susi": {
        id: "1678679",
        rating: "2.4",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "---",
    },
    "Osterberg, Rennesa": {
        id: "1690568",
        rating: "3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Taipale, Kaisa": {
        id: "1699007",
        rating: "2.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Thornhill, Theodore": {
        id: "1700637",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Gallas, Ron": {
        id: "1703223",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Kim, John": {
        id: "1706820",
        rating: "3.8",
        reviews: 0,
        difficulty: "1.8",
        wouldTakeAgain: "---",
    },
    "Naito, Jonathan": {
        id: "1711261",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "Gallego, Carlos": {
        id: "1711904",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Vandiver, Rebecca": {
        id: "1713088",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Westerman, Molly": {
        id: "1716021",
        rating: "1",
        reviews: 0,
        difficulty: "5",
        wouldTakeAgain: "---",
    },
    "Ramirez, Catherine": {
        id: "1728684",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Purin, Marju": {
        id: "1756513",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Veltri, Carlo": {
        id: "1761226",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Lenertz, Lisa": {
        id: "1761455",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Wong, KA": {
        id: "1762095",
        rating: "5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Sundby, Mark": {
        id: "1769353",
        rating: "4",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "80",
    },
    "Weeks, Michon": {
        id: "1769992",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Feeney, Megan": {
        id: "1773393",
        rating: "3.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Bowers, Lisa": {
        id: "1776583",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "100",
    },
    "McDonald, Erik": {
        id: "1783206",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Olszewski, Jerry": {
        id: "1786934",
        rating: "5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "---",
    },
    "Kodl, Molly": {
        id: "1787026",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Zayas, Roberto": {
        id: "1790641",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Hirsch, Richard": {
        id: "1793933",
        rating: "3.9",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Stein, Sarah": {
        id: "1794667",
        rating: "2.5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Hoffmann, Kathy": {
        id: "1799739",
        rating: "2",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Richardson, Brandt": {
        id: "1807576",
        rating: "3.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Paton, Priscilla": {
        id: "1820968",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Snyder, Edward": {
        id: "1823754",
        rating: "2.8",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "McGavran, James": {
        id: "1824492",
        rating: "5",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Erickson, Jake": {
        id: "1841688",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Binder, Seth": {
        id: "1843146",
        rating: "3.3",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "67",
    },
    "Fogarty, Keir": {
        id: "1845804",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "---",
    },
    "Vork, Robert": {
        id: "1848657",
        rating: "2.3",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Krouk, Dean": {
        id: "1848661",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Marlier, Elodie": {
        id: "1851503",
        rating: "4.2",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "79",
    },
    "Smalling, Susan": {
        id: "1857214",
        rating: "5",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Whittinghill, Kyle": {
        id: "1872892",
        rating: "1.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Diveris, Kosmas": {
        id: "1874057",
        rating: "4.8",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "100",
    },
    "Moya, Reinaldo": {
        id: "1883928",
        rating: "2.3",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "---",
    },
    "Scholten, Marc": {
        id: "1890834",
        rating: "3.8",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Clark, Rachel": {
        id: "1902037",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Manner, Jennifer": {
        id: "1921256",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Wiebold, Matt": {
        id: "1922106",
        rating: "4.9",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "---",
    },
    "Zhou, Ying": {
        id: "1924010",
        rating: "4.8",
        reviews: 0,
        difficulty: "1.6",
        wouldTakeAgain: "100",
    },
    "Boyd, Scott": {
        id: "1932055",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Musselman, Jessica": {
        id: "1933370",
        rating: "3",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "---",
    },
    "Swanson, Kathryn": {
        id: "1944580",
        rating: "4.2",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "82",
    },
    "Creech, Ken": {
        id: "1962534",
        rating: "4",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Center, Alyson": {
        id: "1964338",
        rating: "3.3",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "25",
    },
    "Filler, Emily": {
        id: "1969266",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Manzoni, Carla": {
        id: "1983108",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Benson, Joe": {
        id: "1984301",
        rating: "2.4",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Anderson, Joshua": {
        id: "1984780",
        rating: "3",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "29",
    },
    "Fischer, Sylvia": {
        id: "1985995",
        rating: "4.3",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Johnson, Anna": {
        id: "1985996",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "100",
    },
    "Mohl, Emily": {
        id: "1994733",
        rating: "2",
        reviews: 0,
        difficulty: "3.9",
        wouldTakeAgain: "---",
    },
    "Vendetti, Maria": {
        id: "2000760",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "60",
    },
    "Everson, Daniel": {
        id: "2003488",
        rating: "3",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "---",
    },
    "Creech, Kenneth": {
        id: "2005375",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Wilcox, Jennifer": {
        id: "2011829",
        rating: "3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Anquandah, George": {
        id: "2040235",
        rating: "1.9",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "Korynta, Kyle": {
        id: "2040243",
        rating: "3.5",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "67",
    },
    ", Thomas": {
        id: "2051234",
        rating: "1.9",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Adhikari, Prabal": {
        id: "2052063",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "76",
    },
    "Dittmer, Adam": {
        id: "2052591",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "56",
    },
    "Bateza, Anthony": {
        id: "2058474",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "80",
    },
    "Patterson, Juliet": {
        id: "2059374",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Pompeian, Edward": {
        id: "2060015",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "58",
    },
    "Rippley, Lavern": {
        id: "2061068",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Mummey, Kevin": {
        id: "2064614",
        rating: "2.8",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "45",
    },
    "Marsh, Jason": {
        id: "2076676",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "84",
    },
    "Ryu, Hwayeon": {
        id: "2083155",
        rating: "1.6",
        reviews: 0,
        difficulty: "4.6",
        wouldTakeAgain: "---",
    },
    "Tun, Molly": {
        id: "2091134",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "78",
    },
    "Tasson, Jay": {
        id: "2091511",
        rating: "4.8",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Garrett, Kristina": {
        id: "2092253",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Franson, Sally": {
        id: "2092789",
        rating: "4.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Alderks, Elisabeth": {
        id: "2096080",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Moore, Lisa": {
        id: "2102366",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Epstein, Louis": {
        id: "2102898",
        rating: "4.5",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "92",
    },
    "Randall, Amanda": {
        id: "2107941",
        rating: "4.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Nordfjord, Bjorn": {
        id: "2117294",
        rating: "3.8",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "80",
    },
    "Ophaug, John": {
        id: "2131181",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Zanon, Ksenia": {
        id: "2132594",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Strand, Kendra": {
        id: "2137381",
        rating: "4",
        reviews: 0,
        difficulty: "1.3",
        wouldTakeAgain: "67",
    },
    "Fuerstein, Michael": {
        id: "2140255",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "75",
    },
    "Whitlatch, Lisa": {
        id: "2147243",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Pahnke, Anthony": {
        id: "2150067",
        rating: "3.6",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "63",
    },
    "Maeda, Dana": {
        id: "2153262",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Cole, Steven": {
        id: "2165072",
        rating: "5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Elangovan, Vinayak": {
        id: "2169377",
        rating: "3.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Hibbard, Therees": {
        id: "2170544",
        rating: "4.8",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Anderegg, Francesca": {
        id: "2171523",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Nagamatsu, Jeremy": {
        id: "2175989",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Heidgerken, Benjamin": {
        id: "2181583",
        rating: "2.7",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "22",
    },
    "Choi, Vivian": {
        id: "2186602",
        rating: "3.4",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "60",
    },
    "Erickson, Anna": {
        id: "2189835",
        rating: "2.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "34",
    },
    "Greenberg, Paul": {
        id: "2195497",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Shields, Nathan": {
        id: "2209714",
        rating: "3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "34",
    },
    "Larsen, Amy": {
        id: "2209725",
        rating: "3.7",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "67",
    },
    "Barkve, Marit": {
        id: "2209829",
        rating: "3",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "50",
    },
    "Costanzi, Barry": {
        id: "2210044",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Mokdad, Linda": {
        id: "2219844",
        rating: "4.7",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "84",
    },
    "Collins, Tim": {
        id: "2223291",
        rating: "5",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Wright, Matthew": {
        id: "2225675",
        rating: "5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Hatting, Kayla": {
        id: "2228108",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Kanewischer, Erica": {
        id: "2231807",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Bernardin, Thomas": {
        id: "2231808",
        rating: "4.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Ward, Sean": {
        id: "2244554",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Gibbs, Michelle": {
        id: "2246998",
        rating: "4",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Pell, Bruce": {
        id: "2247016",
        rating: "5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Huehn, Susan": {
        id: "2249651",
        rating: "2.7",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "67",
    },
    "Fluerimond, Vladimir": {
        id: "2261730",
        rating: "2.3",
        reviews: 0,
        difficulty: "3.8",
        wouldTakeAgain: "25",
    },
    "Bucciaglia, Nicolette": {
        id: "2287320",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "100",
    },
    "Williams, Arneshia": {
        id: "2288583",
        rating: "1.8",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "13",
    },
    "Radtke, Mitchell": {
        id: "2296022",
        rating: "5",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "100",
    },
    "Rohn, Matthew": {
        id: "2299968",
        rating: "2",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Noor, Shahid": {
        id: "2311644",
        rating: "1.8",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "17",
    },
    "Pettitt, Beth": {
        id: "2318752",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "84",
    },
    "Grodzicki, William": {
        id: "2340105",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Walmsley, David": {
        id: "2347576",
        rating: "5",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Peabody, Seth": {
        id: "2351902",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "80",
    },
    "Meinzer, Melanie": {
        id: "2357264",
        rating: "2.7",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "45",
    },
    "Holbein, Jennifer": {
        id: "2358501",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "67",
    },
    "furnstein, michael": {
        id: "2361923",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Rambachan, Anantanand": {
        id: "2362372",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Gottsegen, Michael": {
        id: "2378362",
        rating: "2.1",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "25",
    },
    "Conger, Andrea": {
        id: "2379178",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Cunningham, Maurella": {
        id: "2379201",
        rating: "5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "100",
    },
    "Tegtmeyer, Judy": {
        id: "2379213",
        rating: "5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "100",
    },
    "Skeba, Mark": {
        id: "2379664",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Elias, Christopher": {
        id: "2381308",
        rating: "4.9",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "Spooner, Bridget": {
        id: "2382512",
        rating: "5",
        reviews: 0,
        difficulty: "1",
        wouldTakeAgain: "100",
    },
    "Yoshioka, Livi": {
        id: "2383031",
        rating: "4.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "84",
    },
    "Kruse, Dale": {
        id: "2385197",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Pazian, Erika": {
        id: "2398920",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Briand, Cedric": {
        id: "2404899",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "75",
    },
    "Holt, Ketty": {
        id: "2411002",
        rating: "2.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "50",
    },
    "Johnson, Susie": {
        id: "2411004",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Feldt, Alison": {
        id: "2411005",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Kheshgi, Rehanna": {
        id: "2411007",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Draxler, Bridget": {
        id: "2414893",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Wondemagegnehu, Tesfa": {
        id: "2415371",
        rating: "5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Quimby, Joanne": {
        id: "2415987",
        rating: "5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Akimoto, Hiroe": {
        id: "2415990",
        rating: "5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Jorgenson, Kiara": {
        id: "2419118",
        rating: "3",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "60",
    },
    "Jensen, Elizabeth": {
        id: "2429032",
        rating: "4.3",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Pollard, Vernon": {
        id: "2445018",
        rating: "4.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Nekbakhtshoev, Navruz": {
        id: "2445141",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Scopatz, Dana": {
        id: "2445396",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Harris, Colin": {
        id: "2447215",
        rating: "4.8",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Schmidt, Bryan": {
        id: "2447421",
        rating: "1.3",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "---",
    },
    "Lee, Sooyoung": {
        id: "2450370",
        rating: "2.2",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "20",
    },
    "Hanson, Marit": {
        id: "2450371",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "84",
    },
    "Holgerson, Meredith": {
        id: "2459306",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "100",
    },
    "LeBlanc, Diane": {
        id: "2461450",
        rating: "3",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Bozeman, Chassidy": {
        id: "2463701",
        rating: "5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Adolph, Alden": {
        id: "2477923",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Cisar, Mary": {
        id: "2478599",
        rating: "4.3",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Brandon, Miranda": {
        id: "2478970",
        rating: "3.5",
        reviews: 0,
        difficulty: "1.5",
        wouldTakeAgain: "50",
    },
    "David, Marc": {
        id: "2490973",
        rating: "4.2",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "80",
    },
    "Mendez, Melissa": {
        id: "2492728",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Bauer, Theresa": {
        id: "2492892",
        rating: "1",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Pearce, Anna": {
        id: "2528558",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Book, Cynthia": {
        id: "2509930",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Petterson, Juliet": {
        id: "2513155",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Selinsky, Peter": {
        id: "2517720",
        rating: "3.3",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "67",
    },
    "Henrikson, Ingunn": {
        id: "2521139",
        rating: "4.6",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Johnston, PJ": {
        id: "2524791",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Lee, Norman": {
        id: "2524998",
        rating: "3.4",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "45",
    },
    "Styles, Monica": {
        id: "2530285",
        rating: "2.3",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "34",
    },
    "Jessup, David": {
        id: "2531533",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "50",
    },
    "Guglielmo, Mark": {
        id: "2535999",
        rating: "1.2",
        reviews: 0,
        difficulty: "1.7",
        wouldTakeAgain: "---",
    },
    "Foster, Veronica": {
        id: "2536272",
        rating: "3",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Ziegler, Kathy": {
        id: "2546340",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Montgomery, Stephanie": {
        id: "2550598",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Roesselet, Kevin": {
        id: "2551389",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Ryan, Hannah": {
        id: "2560189",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "75",
    },
    "Foster, Peter": {
        id: "2560822",
        rating: "3.3",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "67",
    },
    "Butler, Megan": {
        id: "2562183",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Istephanous, Bronwyn": {
        id: "2577316",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "100",
    },
    "Benson, Jessica": {
        id: "2583359",
        rating: "5",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Svynarenko, Anton": {
        id: "2585699",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Spiker, Christina": {
        id: "2586178",
        rating: "5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Miller, Jesse": {
        id: "2586232",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Shaiman, Jennifer": {
        id: "2590155",
        rating: "2.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Roith, Joseph": {
        id: "2592594",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Munoz, Avi": {
        id: "2593350",
        rating: "4",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "100",
    },
    "Cilizoglu, Menevis": {
        id: "2605364",
        rating: "3",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Demas, James": {
        id: "1586191",
        rating: "4.1",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "58",
    },
    "Munoz, Avram": {
        id: "2598964",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Paddleford, Nancy": {
        id: "1665450",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "100",
    },
    "Mahr, Tim": {
        id: "170754",
        rating: "4",
        reviews: 0,
        difficulty: "3.6",
        wouldTakeAgain: "100",
    },
    "Rodland, Catherine": {
        id: "416959",
        rating: "4.6",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "84",
    },
    "Borovsky, Brian": {
        id: "894125",
        rating: "4.6",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Castro, David": {
        id: "767613",
        rating: "5",
        reviews: 0,
        difficulty: "2.9",
        wouldTakeAgain: "100",
    },
    "Bouxsein, Hilary": {
        id: "2418227",
        rating: "3.2",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "75",
    },
    "Titus, Mary": {
        id: "475697",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "St., Thomas": {
        id: "1839519",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "---",
    },
    "O'Dell, Maggie": {
        id: "137021",
        rating: "2.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "80",
    },
    "Tegtmeyer-Pak, Katherine": {
        id: "343076",
        rating: "3.7",
        reviews: 0,
        difficulty: "4.5",
        wouldTakeAgain: "34",
    },
    "Fure-Slocum, Eric": {
        id: "395122",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "E., Charles": {
        id: "430887",
        rating: "2.8",
        reviews: 0,
        difficulty: "4.2",
        wouldTakeAgain: "50",
    },
    "Nordstrom-Loeb, Bruce": {
        id: "461769",
        rating: "4.8",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Barnes-Karol, Gwen": {
        id: "469844",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "84",
    },
    "De, Gary": {
        id: "471385",
        rating: "3.6",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Peterson, Karen": {
        id: "531441",
        rating: "4.3",
        reviews: 0,
        difficulty: "2.2",
        wouldTakeAgain: "50",
    },
    "Dan, Dr.": {
        id: "587359",
        rating: "2.8",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "---",
    },
    "O'Leary, Margaret": {
        id: "607189",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "---",
    },
    "Murray-Close, Dianna": {
        id: "902905",
        rating: "4.7",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "---",
    },
    "Yuedong, Faye": {
        id: "935387",
        rating: "4.1",
        reviews: 0,
        difficulty: "2.4",
        wouldTakeAgain: "100",
    },
    "Lane-Getaz, Sharon": {
        id: "1190278",
        rating: "2.7",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "50",
    },
    "Grajales-Diez, Jorge": {
        id: "1199866",
        rating: "2.1",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Villate-Isaza, Alberto": {
        id: "1344376",
        rating: "4.2",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "---",
    },
    "Van, David": {
        id: "1403428",
        rating: "4.9",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "---",
    },
    "Eudes, Jean": {
        id: "1547925",
        rating: "2.9",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "---",
    },
    "Munoz-Hutchinson, Daniel": {
        id: "1560516",
        rating: "3.6",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "43",
    },
    "O'Connor, Jonathon": {
        id: "1661351",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "50",
    },
    "Caldesi-Valeri, Valerio": {
        id: "1729989",
        rating: "5",
        reviews: 0,
        difficulty: "5",
        wouldTakeAgain: "---",
    },
    "Al, Ibtesam": {
        id: "1741767",
        rating: "4.5",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "100",
    },
    "Stack-Nelson, Judith": {
        id: "1787530",
        rating: "2",
        reviews: 0,
        difficulty: "3.5",
        wouldTakeAgain: "100",
    },
    "Bridges, William": {
        id: "1787544",
        rating: "4.4",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Boehm, Laura": {
        id: "1841354",
        rating: "2.3",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "---",
    },
    "Joslin, Isaac": {
        id: "1889702",
        rating: "4.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "Petok, Jessica": {
        id: "2015051",
        rating: "3.9",
        reviews: 0,
        difficulty: "3.7",
        wouldTakeAgain: "69",
    },
    "(Casey), William": {
        id: "2100007",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "72",
    },
    "Shirkey-Son, Nicole": {
        id: "2113282",
        rating: "2.8",
        reviews: 0,
        difficulty: "4.1",
        wouldTakeAgain: "100",
    },
    "Nelson, Peter": {
        id: "2114589",
        rating: "3.4",
        reviews: 0,
        difficulty: "3.2",
        wouldTakeAgain: "60",
    },
    "Amugongo, Sara": {
        id: "2135185",
        rating: "1.9",
        reviews: 0,
        difficulty: "4.4",
        wouldTakeAgain: "25",
    },
    "Kapelke, Anabel": {
        id: "2145352",
        rating: "3.5",
        reviews: 0,
        difficulty: "2",
        wouldTakeAgain: "---",
    },
    "(Liz), Elizabeth": {
        id: "2146657",
        rating: "3.5",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "---",
    },
    "Schalliol, David": {
        id: "2168838",
        rating: "3.5",
        reviews: 0,
        difficulty: "3.1",
        wouldTakeAgain: "88",
    },
    "Dillon, Brianna": {
        id: "2186648",
        rating: "1.8",
        reviews: 0,
        difficulty: "4.8",
        wouldTakeAgain: "20",
    },
    "Nelson, Daniel": {
        id: "2188886",
        rating: "3.4",
        reviews: 0,
        difficulty: "2.6",
        wouldTakeAgain: "100",
    },
    "Shih, Hsiang-Lin": {
        id: "2199644",
        rating: "4.5",
        reviews: 0,
        difficulty: "2.5",
        wouldTakeAgain: "88",
    },
    "Stover, Mark": {
        id: "2199796",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Sanchez-Gonzalez, Rodrigo": {
        id: "2228111",
        rating: "5",
        reviews: 0,
        difficulty: "2.8",
        wouldTakeAgain: "100",
    },
    "Van, Ben": {
        id: "2243988",
        rating: "4.5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "50",
    },
    "Eisinger, Robert": {
        id: "2328149",
        rating: "3.7",
        reviews: 0,
        difficulty: "2.7",
        wouldTakeAgain: "100",
    },
    "Palmer, James": {
        id: "2332569",
        rating: "4.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Moreno-Diaz, Carmen": {
        id: "2377406",
        rating: "3.7",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "67",
    },
    "Humm, Courtney": {
        id: "2451612",
        rating: "5",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Helms, Kyle": {
        id: "2458340",
        rating: "4.7",
        reviews: 0,
        difficulty: "2.3",
        wouldTakeAgain: "100",
    },
    "Page, Theodore": {
        id: "2479368",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Atiyat, Al": {
        id: "2515256",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "Figueroa-Ray, Kelly": {
        id: "2530300",
        rating: "2.2",
        reviews: 0,
        difficulty: "3.3",
        wouldTakeAgain: "34",
    },
    "Dorer, Kari": {
        id: "2531330",
        rating: "4",
        reviews: 0,
        difficulty: "4",
        wouldTakeAgain: "100",
    },
    "Hill, Amy": {
        id: "2603581",
        rating: "4",
        reviews: 0,
        difficulty: "3",
        wouldTakeAgain: "100",
    },
    "Barnes-Karol, Gwendolyn": {
        id: "2609165",
        rating: "N/A",
        reviews: 0,
        difficulty: "",
        wouldTakeAgain: "---",
    },
    "O'Conner, Jonathan": {
        id: "1681438",
        rating: "3",
        reviews: 0,
        difficulty: "4.3",
        wouldTakeAgain: "25",
    },
    "Medina-Vilarino, Kristina": {
        id: "1909995",
        rating: "4.3",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "80",
    },
    "Bobb, James": {
        id: "2267000",
        rating: "4.5",
        reviews: 0,
        difficulty: "1.5",
        wouldTakeAgain: "100",
    },
    "Gothmann, Anne": {
        id: "2342830",
        rating: "4.4",
        reviews: 0,
        difficulty: "3.4",
        wouldTakeAgain: "80",
    },
};
