const UNMATCHED_PROFESSORS = {
    "Al Atiyat,": "Atiyat, Al",
    "Bansah, Marcus": "",
    "Berry, Anne": "",
    "Beussman, Douglas": "Beussman, Douglass",
    "Bi, Hui": "",
    "Billingsley, Tyler": "",
    "Bosch, Kelsey": "",
    "Bostwick, Christi": "",
    "Breckbill, Anne": "",
    "Brentrup, Jennifer": "",
    "Buzza, Timothy": "",
    "Chamseddine, Ali": "",
    "Chapp, Christopher": "Chapp, Chris",
    "Christie, Sian": "",
    "Clifton, Sara": "",
    "Coughlin, Jenna": "", //
    "Davila, Jaime": "",
    "DeFries, Brett": "",
    "Dulkin, Ryan": "",
    "Eichberger, Ryan": "",
    "Elsaesser, Carl": "",
    "Engleman, Tracey": "", //
    "Frary, Whitney": "",
    "Fyfe, Charles": "",
    "Garner, Leigh": "",
    "Goedde, Richard": "Goedde, Rick",
    "Hagen, Chloe": "",
    "Hakim Javadi,": "",
    "Hansen, Peter": "",
    "Hazlett, Eric": "",
    "Hill Cosimini, Amy M.": "",
    "Hofrenning, Daniel": "",
    "Huff, Charles": "Huff, Chuck",
    "Johnson, Ida": "",
    "Joiner, Cassandra": "",
    "Killackey, Sean": "",
    "Kim, April": "",
    "Kosmoski, Daniel": "Kosmoski, Dan",
    "Kwon Dobbs,": "",
    "LaFond-Hudson, Sophia": "",
    "Lagerquist, L.": "Lagerquist, Deane",
    "Lee, Jerry": "",
    "Leer, Elizabeth": "",
    "Leonard, Courtney": "",
    "Luedtke, Allison": "",
    "Mahr, Timothy": "Mahr, Tim",
    "Marahatta, Ram": "",
    "Math, Jonna": "",
    "McDonald, Matthew": "",
    "McKelvey, Steven": "",
    "Merritt, Adrienne": "",
    "Moeller, Johnathan": "",
    "Mooy, Anna": "",
    "Moreno-Diaz, Maria": "Moreno-Diaz, Carmen",
    "Mugabe, Douglas": "",
    "Munoz-Hutchinson, Danny": "Munoz-Hutchinson, Daniel",
    "Nesbit, Scott": "Nesbit, Coach",
    "Pate, SooJin": "",
    "Perron, Kristen": "",
    "Pfarr-Baker, Rosemary": "",
    "Pinto-Handler, Sergio": "",
    "Rainey, Timothy M. II.": "",
    "Roberts, Janice": "",
    "Sanchez Gonzalez,": "Sanchez-Gonzalez, Rodrigo",
    "Sanford, James": "",
    "Schmid, Caitlin": "",
    "Scholz-Carlson, Miriam": "",
    "Schwinefus, Jeffrey": "Schwinefus, Jeff",
    "Shea, Kathleen": "Shea, Kathy",
    "Sonnega, William": "Sonnega, Bill",
    "Steed, Kathryn": "",
    "Swedin, Rachel": "",
    "Tcacenco, Andrei": "",
    "Tegtmeyer Pak, Katherine S.": "Tegtmeyer-Pak, Katherine",
    "Tegtmeyer, Judith": "Tegtmeyer, Judy",
    "Thalhammer, Kristina": "Thalhammer, Kris",
    "Thresher, Tanya": "",
    "Tuley, Katherine": "",
    "Umbanhowar, Charles": "",
    "Vosburg, Nora": "",
    "Wall, Travis": "",
    "Walter, Gregory": "Walter, Greg",
    "Watson, Jill": "",
    "Westler, Brendon": "",
    "Wilkerson, Karen": "",
    "Williamson, Thomas": "",
    "Wilson, Karen": "",
    "Wong, Ka": "Wong, KA",
    "Wood, Adam": "",
    "Wright, Robin": "",
    "Yoshioka-Maxwell, Olivia": "Yoshioka, Livi",
    "von Bibra,": "Vonbibra, Anne",
    "Ananda-Owens, Kathryn": "",
    "Cornejo, Cecilia": "",
    "Stephens, Emery": "",
    "Dowd, Adam": "",
    "Gill, Emily": "",
    "Granquist, Kathy": "",
    "Haecker, Arthur": "",
    "Hazlett, Emily": "",
    "McClung, James": "",
    "McDonald, Sarah": "",
};
